name:                homework1
version:             0.1.0.0
github:              "WalkerCodeRanger/haskell-exercises-cis194-spring13"
license:             BSD3
author:              "Jeff Walker"
maintainer:          "Jeff@WalkerCodeRanger.com"
copyright:           "2019 Jeff Walker"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/homework1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  homework1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework1

tests:
  homework1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework1
